---
name: p-spring-cloud-services-04d017acad065e8b5dac
director_uuid: ad01a750-504c-4e13-9557-960d2a013691
releases:
- name: spring-cloud-broker
  version: 1.0.3-build.13
networks:
- name: default
  subnets:
  - range: 10.0.16.0/20
    gateway: 10.0.16.1
    dns:
    - 10.0.0.2
    static: []
    reserved:
    - 10.0.16.2-10.0.16.84
    - 10.0.16.86-10.0.16.94
    - 10.0.16.98-10.0.31.254
    cloud_properties:
      virtual_network_name: boshvnet-crp # <--- Replace with virtual network name
      subnet_name: CloudFoundry # <--- Replace with subnet name for cloud foundry VMs
resource_pools:
- name: deploy-service-broker
  stemcell:
    name: bosh-azure-hyperv-ubuntu-trusty-go_agent
    version: latest
  network: default
  cloud_properties:
    instance_type: Standard_D1
    ephemeral_disk:
      size: 2048
  env:
    bosh:
      password: "$6$59df1961c276f19f$Ag5n01SpoO1BQkYQkBhbO0ncKgNWHHb.qEKYeE2RlvnLGMyjQ4CicGOTG7YzlHNTgaF.kUbp8LmiiWkpNk5hc1"
- name: register-service-broker
  stemcell:
    name: bosh-azure-hyperv-ubuntu-trusty-go_agent
    version: latest
  network: default
  cloud_properties:
    instance_type: Standard_D1
    ephemeral_disk:
      size: 2048
  env:
    bosh:
      password: "$6$e42d9847f76ec553$O8pqEnEJsY7A5kupQrjMozJj3jPE9KGlXAO/ywVrzq2MEoaLPQxuUvcOiyrnvwQ/GypUUIIskCnYrFmopqSKx1"
- name: destroy-service-broker
  stemcell:
    name: bosh-azure-hyperv-ubuntu-trusty-go_agent
    version: latest
  network: default
  cloud_properties:
    instance_type: Standard_D1
    ephemeral_disk:
      size: 1024
  env:
    bosh:
      password: "$6$03df082b2c043209$RkXCTKUUnDNuNcRDKSU4iPeMkqu2vbjQ/FU5VgXIJfLvqaBKb4uxVQNpXFg.oKQVzye3NWcJ6LBp4dUlWqNEk/"
compilation:
  reuse_compilation_vms: true
  workers: 1
  network: default
  cloud_properties:
    instance_type: Standard_D2_V2
    ephemeral_disk:
      size: 2048
update:
  canaries: 1
  canary_watch_time: 30000-300000
  update_watch_time: 30000-300000
  max_in_flight: 1
  max_errors: 2
  serial: true
jobs:
- name: deploy-service-broker
  templates:
  - name: deploy-service-broker
    release: spring-cloud-broker
  lifecycle: errand
  instances: 1
  resource_pool: deploy-service-broker
  networks:
  - name: default
    default:
    - dns
    - gateway
  properties:
    domain: pcfazure.com
    app_domains:
    - pcfazure.com
    ssl:
      skip_cert_verify: true
    spring_cloud_broker:
      product_name: 
      app_name: 
      app_uri: 
      broker:
        org_name: 
        space_name: 
        user: c0b253e33e0e6f547c24
        password: baae5d617be5dddcd9ac
        max_instances: 100
      worker:
        client_id: 
        client_secret: b1777147bfab3e5d104c
        user: admin
        password: a53e794fb60e272e263e
      instances:
        org_name: 
        space_name: 
        instances_user: p-spring-cloud-services
        instances_password: c5eeaeb55ce4406d2c68
      app_push:
        timeout: 180
        memory: 
      broker_dashboard_secret: e80f4fe7a3d3ee8cf970
      persistence_store_type: 
      encryption_key: f135888007e148da7557
      cf:
        admin_user: admin
        admin_password: a895cb2917e53e8b6dea
      uaa:
        admin_client_id: admin
        admin_client_secret: cc573622af3ad23fe3bb
  update:
    max_in_flight: 1
- name: register-service-broker
  templates:
  - name: register-service-broker
    release: spring-cloud-broker
  lifecycle: errand
  instances: 1
  resource_pool: register-service-broker
  networks:
  - name: default
    default:
    - dns
    - gateway
  properties:
    domain: pcfazure.com
    app_domains:
    - pcfazure.com
    ssl:
      skip_cert_verify: true
    spring_cloud_broker:
      product_name: 
      broker:
        org_name: 
        space_name: 
        user: c0b253e33e0e6f547c24
        password: baae5d617be5dddcd9ac
        plan_names: 
      app_name: 
      app_uri: 
      encryption_key: f135888007e148da7557
      cf:
        admin_user: admin
        admin_password: a895cb2917e53e8b6dea
      uaa:
        admin_client_id: admin
        admin_client_secret: cc573622af3ad23fe3bb
  update:
    max_in_flight: 1
- name: destroy-service-broker
  templates:
  - name: destroy-service-broker
    release: spring-cloud-broker
  lifecycle: errand
  instances: 1
  resource_pool: destroy-service-broker
  networks:
  - name: default
    default:
    - dns
    - gateway
  properties:
    domain: pcfazure.com
    app_domains:
    - pcfazure.com
    ssl:
      skip_cert_verify: true
    spring_cloud_broker:
      product_name: 
      broker:
        org_name: 
        space_name: 
        user: c0b253e33e0e6f547c24
        password: baae5d617be5dddcd9ac
        plan_names: 
      worker:
        client_id: 
        client_secret: d894a1fbf4d27443282a
      instances:
        org_name: 
        space_name: 
        instances_user: p-spring-cloud-services
      app_name: 
      app_uri: 
      encryption_key: f135888007e148da7557
      cf:
        admin_user: admin
        admin_password: a895cb2917e53e8b6dea
      uaa:
        admin_client_id: admin
        admin_client_secret: cc573622af3ad23fe3bb
  update:
    max_in_flight: 1
disk_pools: []
