bosh run errand smoke-tests
bosh run errand push-apps-manager
bosh run errand push-app-usage-service
bosh run errand notifications
bosh run errand notifications-tests
bosh run errand notifications-ui
bosh run errand notifications-ui-tests
bosh run errand autoscaling
bosh run errand autoscaling-register-broker
