bosh upload stemcell https://s3.amazonaws.com/bosh-azure-stemcells/bosh-stemcell-3184-azure-hyperv-ubuntu-trusty-go_agent.tgz
bosh upload release releases/cf-225.7.tgz
bosh upload release releases/cf-autoscaling-28.tgz
bosh upload release releases/cf-mysql-23.tgz
bosh upload release releases/diego-0.1441.2.tgz
bosh upload release releases/etcd-release-18.tgz
bosh upload release releases/garden-linux-0.330.0.tgz
bosh upload release releases/push-apps-manager-release-397.tgz
bosh upload release releases/notifications-19.tgz
bosh upload release releases/notifications-ui-10.tgz
